{"name": "Проверка невозможности создания пользователя с существующим логином", "status": "passed", "description": "Запрос на создание пользователя, который уже существует в системе, возвращает ошибку с кодом 403 и текстом ответа 'User already exists'", "steps": [{"name": "Проверка статуса ответа", "status": "passed", "parameters": [{"name": "response", "value": "<Response [403]>"}, {"name": "code", "value": "<HTTPStatus.FORBIDDEN: 403>"}], "start": 1707684995457, "stop": 1707684995457}, {"name": "Проверка ответа 'message'", "status": "passed", "parameters": [{"name": "response", "value": "<Response [403]>"}, {"name": "key", "value": "'message'"}, {"name": "text", "value": "'User already exists'"}], "start": 1707684995458, "stop": 1707684995458}], "start": 1707684995007, "stop": 1707684995460, "uuid": "4d848d6f-d7a3-4c64-a9d2-43dd8073a3fb", "historyId": "ed6eff12eb34ffb7aacfb9a2d1cc4aa6", "testCaseId": "ed6eff12eb34ffb7aacfb9a2d1cc4aa6", "fullName": "tests.test_user_create.TestCreateUser#test_create_user_existed_login", "labels": [{"name": "feature", "value": "Проверка создания пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_create"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "48236-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_create"}]}